# ============================================================
# Deploy script — Grupo Pedregal Portal E-Commerce V2
# Target: IONOS shared hosting (www.grupopedregal.es)
# Flow: local build → git push → git pull on IONOS server
# ============================================================

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

# ----------------------------------------------------------
# 1. Build frontend (Next.js static export)
# ----------------------------------------------------------
Write-Host "`n=== Building frontend ===" -ForegroundColor Cyan
Set-Location frontend

Remove-Item -Recurse -Force .next, out -ErrorAction SilentlyContinue
$env:NEXT_PUBLIC_API_URL = "https://www.grupopedregal.es"
npx next build
if ($LASTEXITCODE -ne 0) { Write-Host "FRONTEND BUILD FAILED" -ForegroundColor Red; exit 1 }

# ----------------------------------------------------------
# 2. Copy static files to Laravel public/
# ----------------------------------------------------------
Write-Host "`n=== Copying static files to backend/public ===" -ForegroundColor Cyan
$dst = "..\backend\public"

# Directories generated by Next.js static export
$frontendDirs = @(
    "_next",
    "admin",
    "app",
    "carrito",
    "categorias",
    "contacto",
    "login",
    "productos",
    "registro"
)

foreach ($d in $frontendDirs) {
    if (Test-Path "out\$d") {
        Remove-Item -Recurse -Force "$dst\$d" -ErrorAction SilentlyContinue
        Copy-Item -Recurse -Force "out\$d" "$dst\$d"
    }
}

# Root-level files
Copy-Item -Force out\index.html "$dst\index.html"
if (Test-Path out\404.html) { Copy-Item -Force out\404.html "$dst\404.html" }

Write-Host "Static files copied." -ForegroundColor Green

# ----------------------------------------------------------
# 3. Git push
# ----------------------------------------------------------
Write-Host "`n=== Pushing to git ===" -ForegroundColor Cyan
Set-Location ..
git add -A
git commit -m "deploy: update portal e-commerce v2"
git push origin main

# ----------------------------------------------------------
# 4. Update server (SSH to IONOS)
# ----------------------------------------------------------
Write-Host "`n=== Updating server ===" -ForegroundColor Cyan
$sshKey  = "C:\Users\dionisdel\.ssh\ionos_grupopedregal"
$sshHost = "su720237@access-5020300065.webspace-host.com"
$appDir  = "~/public/grupopedregal"

# Pull latest code, run migrations, cache config/routes, create storage link
$remoteCommands = @(
    "cd $appDir",
    "git pull origin main",
    "cd backend",
    "php artisan migrate --force",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan storage:link 2>/dev/null || true",
    "php artisan view:cache"
) -join " && "

ssh -i $sshKey -o BatchMode=yes $sshHost $remoteCommands

# ----------------------------------------------------------
# 5. Done
# ----------------------------------------------------------
Write-Host "`nDEPLOY OK" -ForegroundColor Green

# ----------------------------------------------------------
# MANUAL STEPS (run once on initial setup):
# ----------------------------------------------------------
# Run initial product import from Excel:
#   php artisan import:products "path/to/excel.xlsx"
#
# Run seeders if needed (first deploy only):
#   php artisan db:seed --force
#
# Verify storage link exists:
#   ls -la public/storage
# ----------------------------------------------------------
